apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # type of secret, Opaque is the most common, allows for arbitrary key-value data. 
data:
  mongo-root-username: dXNlcm5hbWU= # base64 encoded, use 'echo -n "username" | base64' in terminal
  mongo-root-password: cGFzc3dvcmQ= # base64 encoded, use 'echo -n "password" | base64' in terminal